# Generated by Django 5.1.3 on 2024-12-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('journalist', 'Journalist'), ('editor', 'Editor'), ('admin', 'Admin')], default='journalist', max_length=20),
        ),
    ]
