# Generated by Django 5.1.3 on 2024-12-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_subtitle_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
