# Generated by Django 5.1.3 on 2024-12-25 04:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))]),
        ),
        migrations.AlterField(
            model_name='article',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))]),
        ),
    ]
